### ISSUE TITLE
Wow, interesting..!

### ISSUE THREAD

**Issue by cambiata** [haxeui/haxeui-xwt#1]
Looking forwart to trying this out..!
Keep up! :-)

Jonas

**Comment by ibilon** [comment]
![snapshot5](https://cloud.githubusercontent.com/assets/3843471/21072906/3427a734-bed1-11e6-93b2-ad1c4cbec67f.png)

It can now run the basic haxeui template, should be working enough to try out soon ;)

**Comment by ianharrigan** [comment]
Can this be closed?
