### ISSUE TITLE
Image can't be displayed

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/haxeui-xwt#6]
## Current Behavior
Displayed an empty window instead of window with picture.

Empty window:
![err1](https://cloud.githubusercontent.com/assets/15020827/23397466/b02cfa48-fda9-11e6-88d7-5e84e2ef5784.png)

Target directory:
![dir](https://cloud.githubusercontent.com/assets/15020827/23397480/be956f5c-fda9-11e6-9597-a77242e7ee2e.png)

## Test app / minimal test case
UI.xml of Image sample:
```
<?xml version="1.0" encoding="utf-8"?>
<image resource="Tux.jpg" />
```
[Image.zip](https://github.com/haxeui/haxeui-xwt/files/806102/Image.zip)

## Your Environment
Haxe 3.4.0
Linux Mint 18.1 x64
hxcs 3.4.0
haxeui-core from git
haxeui-xwt from git

Thanks.

**Comment by r3d9u11** [comment]
I this that solution like for [hxwidgets:issue9](https://github.com/haxeui/haxeui-hxwidgets/issues/9), I'll check it

**Comment by ianharrigan** [comment]
My assumption is yes... And it seems Image is mapped in native.xml, so i think it should be fine.
