### ISSUE TITLE
Compilation failed: Not enough arguments, expected conditionRef:Dynamic

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/haxeui-xwt#8]
Can not compile any example.

## Current Behavior

`$ haxe build.hxml

/home/user/.haxelib_repo/haxeui-xwt/git/haxe/ui/backend/ComponentBase.hx:98: characters 29-106 : Not enough arguments, expected conditionRef:Dynamic`

## Test app / minimal test case

[Samples in github](https://github.com/r3d9u11/haxe-basics/tree/master/9_AdditionalLibraries/9.4_GuiFrameworks/9.4.2_HaxeUI/9.4.2.3_haxeui-xwt/9.4.2.3.1_Components/Button)

## Your Environment

* Version used: Haxe 3.4.2, haxeui-core and haxeui-xwt from git
* Operating System and version: Linux Mint 18.2 x64

Thanks.

**Comment by ibilon** [comment]
Must be a change in haxeui-core, I'll try to update this.

Note that even with that fixed you can't do much with this backend, almost no component work well.
If you need a native haxeui backend there is haxeui-hxwidgets https://github.com/haxeui/haxeui-hxwidgets

**Comment by r3d9u11** [comment]
@ibilon thank you!

**Comment by ibilon** [comment]
Should compile with latest haxeui-core now (at least its validation branch),
but like I said a lot of components are missing.

**Comment by r3d9u11** [comment]
@ibilon another compilation error with latest haxeui-core and haxeui-xwt:

```
$ haxe build.hxml
/home/eugene/.haxelib_repo/haxeui-core/git/haxe/ui/core/TextInput.hx:14: characters 12-33 : Redefinition of variable _textStyle in subclass is not allowed. Previously declared at haxe.ui.backend.TextDisplayBase
```

**Comment by ianharrigan** [comment]
@r3d9u11 - @ibilon 's changes will only work with the validation branch of haxeui-core

**Comment by r3d9u11** [comment]
@ianharrigan @ibilon ah yes, I'm inattentively read: "(at least its validation branch)", sorry :)
